name: bananas_cli
description: A simple command-line application.
version: 0.1.0
homepage: https://github.com/spnda/bananas-cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  crypto: ^3.0.0
  http: ^0.13.1
  open_url: ^2.0.0
  path: ^1.7.0
  tint: ^2.0.0
  interact: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
